---
title: '**Factors Related to Parental Involvement in School**'
author: "Tanesia Beverly, Andy Zukerberg, Erin Murrock"
date: "1/11/2020"
output:
  ioslides_presentation: default
  powerpoint_presentation:
    reference_doc: presentation1.pptx
subtitle: Data Science Institute, American University
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning=FALSE, message=FALSE)
```

## **Parental Involvement In School** 

- Parent involvement is related to success of children in school
- “The research overwhelmingly demonstrates that parent involvement in children's learning is positively related to achievement. Further, the research shows that the more intensively parents are involved in their children's learning, the more beneficial are the achievement effects. This holds true for all types of parent involvement in children's learning and for all types and ages of students.” (cotton and Reed, 1989)   


## **Study Purpose** 

- Bullet 1
- Bullet 2
- Bullet 3

## **PFI Questionnaire**

- Parent and Family Involvement in Education
- Conducted in 2016 by the National Center for Education Statistics
- Collected every two or three years
- 14,075 completed interviews
- Parents respond about a selected child
- Includes homeschooled and enrolled children

## **Research Questions and Hypotheses** 

- What are predictors of parent involvement in school?
- Bullet 2
- Bullet 3

## **Data Cleaning**

- Recoded data to remove valid skips 
- Converted some variables to 0 for no and 1 for yes to facilitate counting
- Removed homeschooled children


## **Participants/Demographics**

- Bullet 1
- Bullet 2
- Bullet 3

## **Analysis**

- Descriptive Statistics
- Dimension Reduction (EFA)
- Regression Analysis

## **Results: Dimensionality Reduction**

- Bullet 1
- Bullet 2
- Bullet 3

## **Predictor Descriptives**

- Bullet 1
- Bullet 2
- Bullet 3

## **Prediction Model**

- Bullet 1
- Bullet 2
- Bullet 3

## **Discussion**

- Bullet 1
- Bullet 2
- Bullet 3

## **Future Implications**

- Bullet 1
- Bullet 2
- Bullet 3

## **THANK YOU!**
